### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by raymondlo84** [NVIDIA/Isaac-GR00T#488]
Followed the instruction here to setup the docker image, but when I run inference it throws an Runtime error. What should I try next?

https://github.com/NVIDIA/Isaac-GR00T/blob/main/docker/README.md

```
Traceback (most recent call last):
  File "/workspace/gr00t/scripts/deployment/standalone_inference_script.py", line 816, in <module>
    main(config)
  File "/workspace/gr00t/scripts/deployment/standalone_inference_script.py", line 653, in main
    policy = Gr00tPolicy(
  File "/workspace/gr00t/gr00t/policy/gr00t_policy.py", line 84, in __init__
    model.to(device=device, dtype=torch.bfloat16)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3698, in to
    return super().to(*args, **kwargs)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 942, in _apply
    param_applied = fn(param)
  File "/workspace/gr00t/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1341, in convert
    return t.to(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

root@6f3ba6d3988d:/workspace/gr00t# uv run python scripts/deployment/standalone_inference_script.py   --model-path nvidia/GR00T-N1.6-3B   --dataset-path demo_data/gr1.PickNPlace   --embodiment-tag GR1   --traj-ids 0 1 2   --inference-mode pytorch   --action-horizon 8
```

**Comment by raymondlo84** [comment]
I'm sure the rest are setup accordingly as it passed the GPU test script?
```
ralo@ddef24c-lcedt:~$ docker run --rm --gpus all nvidia/cuda:12.0.0-base-ubuntu22.04 nvidia-smi
Unable to find image 'nvidia/cuda:12.0.0-base-ubuntu22.04' locally
12.0.0-base-ubuntu22.04: Pulling from nvidia/cuda
0a0d0d55d972: Pull complete 
aece8493d397: Pull complete 
56cb4663b3f5: Pull complete 
6c0deaabac71: Pull complete 
cb5efdcf30fe: Pull complete 
Digest: sha256:4e9da312e1f5affc0ab1b2cb3f1141e163849dcd850d66fe315138e82e85427d
Status: Downloaded newer image for nvidia/cuda:12.0.0-base-ubuntu22.04
Mon Jan  5 23:23:47 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.95.05              Driver Version: 580.95.05      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX PRO 6000 Blac...    Off |   00000000:02:00.0 Off |                  Off |
| 30%   32C    P0             54W /  600W |     832MiB /  97887MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by raymondlo84** [comment]
``` 
pip install --force-reinstall torch==2.7.1+cu128 torchvision==0.22.1+cu128 --extra-index-url https://download.pytorch.org/whl/cu128
```

This fixed it :)
