### ISSUE TITLE
Finetunning Gr00t 1.6 on an RTX5090

### ISSUE THREAD

**Issue by rss-hiverobots** [NVIDIA/Isaac-GR00T#536]
Hello,

I am trying to finetune the Apple PnP with a Unitree_G1 embodiment on a single NVIDIA GeForce RTX 5090 but keep getting a cuda OOM error. I have tried lowering the batch size to 1 but still seems to not be enough.

Has anyone managed to finetune gr00t 1.6 on the NVIDIA GeForce RTX 5090? If so, any help would be appreciated.

**Some extra info that may be useful:**
    "torch==2.7.0",
    "torchvision==0.22.0",
    "torchaudio==2.7.0",

I use flash_attn.

I run the following command:

export NUM_GPUS=1
CUDA_VISIBLE_DEVICES=0 python \
    gr00t/experiment/launch_finetune.py \
    --base-model-path nvidia/GR00T-N1.6-3B \
    --dataset_path examples/GR00T-WholeBodyControl/PhysicalAI-Robotics-GR00T-X-Embodiment-Sim/unitree_g1.LMPnPAppleToPlateDC \
    --embodiment_tag UNITREE_G1 \
    --num-gpus $NUM_GPUS \
    --output_dir /tmp/g1_finetune \
    --save-total-limit 5 \
    --save-steps 2000 \
    --max-steps 2000 \
    --global-batch-size 1 \
    --color-jitter-params brightness 0.3 contrast 0.4 saturation 0.5 hue 0.08 \
    --dataloader-num-workers 0

I use Ubuntu 22.04

Driver Version: 570.211.01     CUDA Version: 12.8   

**ERROR:** 
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 31.34 GiB of which 31.38 MiB is free. Including non-PyTorch memory, this process has 31.14 GiB memory in use. Of the allocated memory 29.52 GiB is allocated by PyTorch, and 1.02 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
  0%|

**Comment by NoNoid** [comment]
I have encountered the same problem, also on a RTX 5090. On a previous generation GPU with Lovelace architecture it works fine.

**Comment by alansrobotlab2** [comment]
Turns out 32gb isn't quite enough for me either.

Switching to paged_adamw_8bit worked for me. ymmv.

make these edits to gr00t/experiment/launch_finetune.py

```bash
config.training.start_from_checkpoint = ft_config.base_model_path
#config.training.optim = "adamw_torch"
config.training.optim = "paged_adamw_8bit"
config.training.gradient_checkpointing = True # Trade compute for memory
```

Then something like

```bash
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True CUDA_VISIBLE_DEVICES=0 uv run \
    gr00t/experiment/launch_finetune.py \
    --base-model-path nvidia/GR00T-N1.6-3B \
    --dataset-path ~/Projects/alfiebot_ws/data/alfiebot.CanDoChallenge \
    --embodiment-tag NEW_EMBODIMENT \
    --modality-config-path ~/Projects/alfiebot_ws/data/alfiebot.CanDoChallenge/alfiebot_config.py \
    --num-gpus 1 \
    --output-dir ./alfie-gr00t \
    --save-total-limit 5 \
    --save-steps 2000 \
    --max-steps 2000 \
    --global-batch-size 16 \
    --gradient-accumulation-steps 32 \
    --dataloader-num-workers 4 \
    --color-jitter-params brightness 0.3 contrast 0.4 saturation 0.5 hue 0.08
```
